# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
